const PDFDocument = require("pdfkit");

/**
 * Streams a transaction receipt PDF directly to an HTTP response.
 * Kept simple/deterministic in v1 — same philosophy as messageBuilder:
 * no fancy templating engine, just a straightforward layout.
 */
function streamTransactionReceipt(res, { businessName, tx }) {
  const doc = new PDFDocument({ size: "A5", margin: 40 });
  doc.pipe(res);

  doc.fontSize(18).text(businessName, { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor("#666").text("Transaction Receipt", { align: "center" });
  doc.moveDown(1.5);

  doc.fillColor("#000").fontSize(11);
  doc.text(`Date: ${new Date(tx.createdAt).toLocaleString("en-IN")}`);
  doc.text(`Customer: ${tx.customerName}`);
  doc.text(`Phone: ${tx.customerPhone}`);
  doc.moveDown();

  doc.fontSize(12).text(`${tx.itemType}: ${tx.quantity} ${tx.unit}`);
  doc.text(`Amount: Rs. ${tx.amount}`);
  doc.text(`Payment Mode: ${tx.paymentMode.toUpperCase()}`);
  if (tx.upiReference) doc.text(`UPI Ref: ${tx.upiReference}`);
  if (tx.notes) doc.text(`Notes: ${tx.notes}`);

  doc.moveDown(2);
  doc.fontSize(9).fillColor("#999").text("Generated by Satyadev Workspace", { align: "center" });

  doc.end();
}

module.exports = { streamTransactionReceipt };
